src/Entity/Parti.php
<?php

namespace App\Entity;

use App\Repository\PoliticienRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PartiRepository")
 * @UniqueEntity(fields={"nom"}, message="Ce parti existe déjà.")
 */
class Parti
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $ID;

    /**
     * @ORM\Column(type="string", length=255, unique = true)
     */
    private $nom;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Politicien", mappedBy="parti")
     */
    private $politiciens;

    public function __construct()
    {
        $this->politiciens = new ArrayCollection();
    }

    public function getID(): ?int
    {
        return $this->ID;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getParite(): int{
        $homme = 0;
        $politiciens = $this->getPoliticiens();

        if(count($politiciens) == 0 )
            return -1;

        foreach($politiciens as $politicien){
            if($politicien->getSexe() === "M")
                $homme++;
        }
        return ceil($homme/count($politiciens)*100);
    }

    public function getAgeMoyen(){
        $ageTotal = 0;
        $politiciens = $this->getPoliticiens();

        if(count($politiciens) == 0 )
            return -1;
        foreach($politiciens as $politicien){
            $ageTotal += $politicien->getAge();
        }
        return ($ageTotal/count($politiciens));
    }

    /**
     * @return Collection|Politicien[]
     */
    public function getPoliticiens(): Collection
    {
        return $this->politiciens;
    }

    public function addPoliticien(Politicien $politicien): self
    {
        if (!$this->politiciens->contains($politicien)) {
            $this->politiciens[] = $politicien;
            $politicien->setParti($this);
        }

        return $this;
    }

    public function removePoliticien(Politicien $politicien): self
    {
        if ($this->politiciens->contains($politicien)) {
            $this->politiciens->removeElement($politicien);
            // set the owning side to null (unless already changed)
            if ($politicien->getParti() === $this) {
                $politicien->setParti(null);
            }
        }

        return $this;
    }
}

src/Form/PartiType.php
<?php

namespace App\Form;

use App\Entity\Parti;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PartiType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Parti::class,
        ]);
    }
}

src/Controller/PartiController.php
<?php

namespace App\Controller;

use App\Entity\Parti;
use App\Entity\Politicien;
use App\Form\PartiType;
use App\Repository\PartiRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/parti")
 */
class PartiController extends AbstractController
{
    /**
     * @Route("/", name="parti_index", methods={"GET"})
     */
    public function index(PartiRepository $partiRepository): Response
    {
        return $this->render('parti/index.html.twig', [
            'partis' => $partiRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="parti_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $parti = new Parti();
        $form = $this->createForm(PartiType::class, $parti);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($parti);
            $entityManager->flush();

            return $this->redirectToRoute('parti_index');
        }

        return $this->render('parti/new.html.twig', [
            'parti' => $parti,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="parti_show", methods={"GET"})
     */
    public function show(Parti $parti): Response
    {
        $politiciens = $parti->getPoliticiens();

        return $this->render('parti/show.html.twig', [
            'parti' => $parti,
            'politiciens' => $parti->getPoliticiens()
        ]);
    }

    /**
     * @Route("/{id}/edit", name="parti_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Parti $parti): Response
    {
        $form = $this->createForm(PartiType::class, $parti);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('parti_index');
        }

        return $this->render('parti/edit.html.twig', [
            'parti' => $parti,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="parti_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Parti $parti): Response
    {
        if($parti->getPoliticiens()->count() !== 0 )
            return $this->render('parti/show.html.twig', [
                'parti' => $parti,
                'politiciens' => $parti->getPoliticiens(),
                "erreur" => "On ne peut pas supprimer un parti qui concerne des politiciens."
            ]);
        if ($this->isCsrfTokenValid('delete'.$parti->getID(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($parti);
            $entityManager->flush();
        }

        return $this->redirectToRoute('parti_index');
    }

    /**
     * @Route("/remove/{id}/{politicien}", name="removePoliticienFromParti")
     */
    public function delPoliticien(Request $request, Parti $parti, Politicien $politicien){

        $manager = $this->getDoctrine()->getManager();

        $parti->removePoliticien($politicien);
        $manager->flush();
        $manager->persist($parti);
        $manager->persist($politicien);

        return $this->redirectToRoute("parti_show", ["id"=>$parti->getID()]);
    }
}

templates/parti/_delete_form.html.twig
<form method="post" action="{{ path('parti_delete', {'id': parti.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');" style="display: inline">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ parti.id) }}">
    <button class="btn red">Delete</button>
</form>

templates/parti/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/parti/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Parti{% endblock %}

{% block body %}
    <h1>Edit Parti</h1>

    {{ include('parti/_form.html.twig', {'button_label': 'Update'}) }}
    {% if is_granted('ROLE_ADMIN') %}
        {{ include('parti/_delete_form.html.twig') }}
    {% endif %}
    <a href="{{ path('parti_index') }}" class="btn-flat">Retour</a>


{% endblock %}

templates/parti/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Parti index{% endblock %}

{% block body %}
    <h1>Parti index</h1>

    <table class="table striped">
        <thead>
            <tr>
                <th>Nom</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for parti in partis %}
            <tr>
                <td>{{ parti.nom }}</td>
                <td>
                    <a href="{{ path('parti_show', {'id': parti.id}) }}"><i class="material-icons">remove_red_eye</i></a>

                    {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_SECRETAIRE')%}
                        <a href="{{ path('parti_edit', {'id': parti.id}) }}"><i class="material-icons">edit</i></a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('parti_new') }}" class="btn">Ajouter</a>
{% endblock %}

templates/parti/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Parti{% endblock %}

{% block body %}
    <h1>Create new Parti</h1>

    {{ include('parti/_form.html.twig') }}

    <a href="{{ path('parti_index') }}" class="btn-flat">Retour</a>

{% endblock %}

templates/parti/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Parti{% endblock %}

{% block body %}
    <h1>Parti</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Nom</th>
                <td>{{ parti.nom }}</td>
            </tr>
            <tr>
                <th>Age moyen</th>
                <td>{{ (parti.ageMoyen == -1 ) ? '-' : parti.ageMoyen }}</td>
            </tr>
            <tr>
                <th>% Femme</th>
                <td>{{ (parti.Parite == -1 ) ? '-' : 100-parti-Parite }}</td>
            </tr>
            <tr>
                <th>% Homme</th>
                <td>{{ (parti.Parite == -1 ) ? '-' : parti-Parite }}</td>
            </tr>
        </tbody>
    </table>

    <h3>Membres du parti</h3>
    {% include 'listeInterne.html.twig' with {'deletePath' : "removePoliticienFromParti", "deleteFrom" : parti} %}




    {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_SECRETAIRE')%}
        <a href="{{ path('parti_edit', {'id': parti.id}) }}" class="btn">edit</a>
    {% endif %}
    {% if is_granted('ROLE_ADMIN') %}
        {{ include('parti/_delete_form.html.twig') }}
    {% endif %}

    <a href="{{ path('parti_index') }}" class="btn-flat">Retour</a>
{% endblock %}

{% block javascripts %}
    {% if erreur is defined %}
        <script>
            M.toast({html: "{{erreur}}"})
        </script>
    {% endif %}
{% endblock %}